### =========================
### SNIPPETS ROUTES
### =========================

### GET all snippets (Done)
GET http://localhost:3000/api/snippets


### GET snippet by id (valid) (Done)
GET http://localhost:3000/api/snippets/1


### GET snippet by id (NOT FOUND test) (Done)
GET http://localhost:3000/api/snippets/9999


### CREATE snippet (POST) (Done)
POST http://localhost:3000/api/snippets
Content-Type: application/json

{
  "title": "New Snippet",
  "contents": "Hello from HTTP file",
  "user_id": 1
}


### UPDATE snippet (PUT) (Done)
PUT http://localhost:3000/api/snippets/11
Content-Type: application/json

{
  "title": "Updated Title",
  "contents": "Updated content"
}


### UPDATE snippet (NOT FOUND) (Done)
PUT http://localhost:3000/api/snippets/9999
Content-Type: application/json

{
  "title": "Does not exist"
}


### DELETE snippet (Done)
DELETE http://localhost:3000/api/snippets/11


### DELETE snippet (NOT FOUND) (Done)
DELETE http://localhost:3000/api/snippets/9999



### =========================
### TAGS ROUTES
### =========================

### GET all tags (Done)
GET http://localhost:3000/api/tags 


### GET tag by id (Done)
GET http://localhost:3000/api/tags/1 


### GET tag NOT FOUND (Done)
GET http://localhost:3000/api/tags/9999


### CREATE tag (Done)
POST http://localhost:3000/api/tags
Content-Type: application/json

{
  "name": "bala bala lang"
}


### UPDATE tag (Done)
PUT http://localhost:3000/api/tags/11
Content-Type: application/json

{
  "name": "pascal"
}


### UPDATE tag NOT FOUND (Done)
PUT http://localhost:3000/api/tags/9999
Content-Type: application/json

{
  "name": "Nothing"
}


### DELETE tag (Done)
DELETE http://localhost:3000/api/tags/11


### DELETE tag NOT FOUND (Done)
DELETE http://localhost:3000/api/tags/9999



### =========================
### SEARCH ROUTES
### =========================

### GET search (all) (Done)
GET http://localhost:3000/search


### GET search with query (Done)
GET http://localhost:3000/search?q=react


### GET search with another query (Done)
GET http://localhost:3000/search?q=sql


### POST search (fields filter - tags) (Done)
POST http://localhost:3000/search
Content-Type: application/json

{
  "fields": {
    "tags": "React"
  }
}


### GET search (ONLY q) (Done)
GET http://localhost:3000/search?q=node


### POST only fields (Done)
POST http://localhost:3000/search
Content-Type: application/json

{
  "fields": {
    "tags": "react"
  }
}

### ERROR (both q + fields)
POST http://localhost:3000/search?q=react
Content-Type: application/json

{
  "fields": {
    "tags": "react"
  }
}